name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0 ğŸŒ‡
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies ğŸ”§
      run: dotnet restore 
    - name: Build ğŸ› ï¸
      run: dotnet build --no-restore
    - name: Automated test ğŸ§ª
      run: dotnet test 

  DeployToDevelop:
 
    name: Deploy
    needs: build
    if: github.event.name == 'push'
    runs-on: ubuntu-latest
    environment: TestEnvironment
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x   
    - name: Restore dependencies ğŸŒ‡
      run: dotnet restore
    - name: Build ğŸ”§
      run: dotnet build --no-restore
    - name: Test ğŸ› ï¸
      run: dotnet test --no-build --verbosity normal
    - name: Deploy to develop ğŸš€
      run: dotnet publish --configuration Release 
    - name: Deploy to staging ğŸ† ğŸ†
      run: dotnet publish --configuration Release 
